### PR TITLE
Create docstrings

### PR DESCRIPTION
**Pull request by jonhealy1**
@gadomski more docstrings! :)
I think I need to see settings in this repo to publish documentation?

### CODE REVIEW

**Review by gadomski — APPROVED** [review]
Fine by me, didn't really do any copy-editing. I added `stac-check` to readthedocs: https://readthedocs.org/dashboard/stac-check. The docs _may_ just work, but you'll probably have to do some additional setup w/ https://docs.readthedocs.io/en/stable/config-file/v2.html and/or Sphinx. But hopefully the hooks are in place to let you do what you need to do -- let me know if not.

**Comment by jonhealy1** [comment]
Thanks Pete! This does help!

**Comment by jonhealy1** [comment]
@gadomski I pushed some changes and you can see them here. Feel free to offer some suggestions. https://stac-check.readthedocs.io/en/latest/

**Comment by gadomski** [comment]
Right on, glad that worked -- LGTM!

**Pull request merged**
